### ISSUE TITLE
Shouldn't ignore jumps/calls over $C000

### ISSUE THREAD

**Issue by VelocityRa** [mmuszkow/gb-disasm#6]
1) The GB has no concept of executable/non executable memory.
2) A lot of test roms write to >= $C000, so gb-disasm doesn't work at all with them.

**Comment by Baekalfen** [comment]
1. True
2. You would practically have to emulate the flow of the program, as you wouldn't know what 0xC000 would contain in advance. And that's best case. It might even change while running.

For the latter case; see Blargg's test ROMs. If I remember correctly, the test code is incrementing the actual opcode (not operands) to determine that every permutation of registers are correct. For the disassembly to make sense, it would have to contain every state of the loop.

If you want to disassemble the RAM areas, the only real solution is to pause an emulator while running, dump the RAM section and run it through the disassembler.


If you are patient, I'm slowly working on debugging functionality for my own emulator (PyBoy). It will likely help you in these cases.

**Comment by VelocityRa** [comment]
>You would practically have to emulate the flow of the program

Yeah that's true, didn't even think about that.

Also, there's no need to dump and run it through the disassembler, bgb's debugger dissasembles it fine if you let it run and navigate to C000.

Thanks, I'm closing this, good luck in your emulation endeavours!
