### ISSUE TITLE
Omits STOP opcodes from output

### ISSUE THREAD

**Issue by raldi** [mmuszkow/gb-disasm#7]
For example, tetris.gb has a "STOP 10" opcode occupying the two bytes at 0x03C4 and 0x03C5, but
`gb-disasm /tmp/tetris.gb -s 3c3 -e 3c7` outputs

```
[0x000003C3] 0x03           INC BC
[0x000003C6] 0xCB 0x11      RL C
```

whereas it should output

```
[0x000003C3] 0x03           INC BC
[0x000003C4] 0x10 0x04      STOP 10
[0x000003C6] 0xCB 0x11      RL C
```

This appears to be due to this for-loop in generator.py:
https://github.com/mmuszkow/gb-disasm/blob/master/src/generator.py#L82

For this opcode (and no others), every single item in VARS misses every if/elif clause, and so nothing happens.

**Comment by mmuszkow** [comment]
Fixed.
